<?xml version="1.0"?>

<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define a number of dimensions using properties -->
  <property name="base_size_x" value="0.70" />
  <property name="base_size_y" value="0.7	0" />
  <property name="base_size_z" value="0.1585" />
  <property name="wheel_length" value="0.05" />
  <property name="wheel_radius" value="0.11" />
  <property name="wheel_offset_x" value="0.20" />
  <property name="wheel_offset_y" value="0.20" />
  <property name="wheel_offset_z" value="-0.03207" />
  
  <property name="base_mesh_scale" value="0.001" />
  
  <property name="PI" value="3.1415" />
     
  <!-- define a wheel -->
  <macro name="wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/>
      <safety_controller k_velocity="10" />
      <origin xyz="${wheel_offset_x} ${reflect*wheel_offset_y} ${wheel_offset_z}" rpy="${reflect*PI/2} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>

  <!-- define a second wheel -->
  <macro name="second_wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel2_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/>
      <safety_controller k_velocity="10" />
      <origin xyz="${-1*wheel_offset_x} ${reflect*wheel_offset_y} ${wheel_offset_z}" rpy="${reflect*PI/2} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel2_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel2_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>

  <!-- The base xacro macro -->
  <macro name="base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${PI/2} " />
        <geometry>
           <mesh filename="package://donaxi_description/meshes/Base.stl" scale="${base_mesh_scale} ${base_mesh_scale} ${base_mesh_scale}" />
        </geometry>
        <material name="${color}" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
           <box size="${base_size_x} ${wheel_offset_y*2 + wheel_length} ${base_size_z}" />
        </geometry>
      </collision>
    </link>
  </macro>
  
  <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 0.001" />
        </geometry>
        <material name="TransparentGreen" />
      </visual>
  </link>
  
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 ${base_size_z/2 + 0.055}" rpy="0 0 0" />        
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

   <!-- Add the drive wheels -->
   <wheel parent="base" suffix="l" reflect="1" color="Black"/>
   <wheel parent="base" suffix="r" reflect="-1" color="Black"/>
   <second_wheel parent="base" suffix="l2" reflect="1" color="Black"/>
   <second_wheel parent="base" suffix="r2" reflect="-1" color="Black"/>


</robot>
